export const MANUAL_SECTIONS = [
  {
    id: 'login',
    group: 'Primeiros Passos',
    title: 'Login e Acesso ao Sistema',
    icon: 'Lock',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/5fdc30c51_generated_image.png',
    topics: [
      {
        title: 'Como fazer login no sistema',
        content: 'A tela de login é o ponto de entrada para o PROFARMA LIBERAAUTO PRO. O acesso é feito com CPF e senha, vinculados à filial onde você trabalha.',
        steps: [
          'Acesse a página inicial do sistema no navegador',
          'Selecione a filial na qual você trabalha no campo "Filial"',
          'Digite seu CPF — a formatação (000.000.000-00) é aplicada automaticamente',
          'Digite sua senha nos campo correspondente',
          'Clique no botão "ENTRAR" para acessar o sistema',
        ],
        tip: 'No primeiro acesso do sistema (sem usuários cadastrados), o sistema cria automaticamente um Administrador Master com o CPF e senha informados.',
      },
      {
        title: 'Esqueci minha senha',
        content: 'Se você esqueceu sua senha, é possível solicitar a redefinição através do link na tela de login.',
        steps: [
          'Na tela de login, clique em "Esqueci minha senha"',
          'Digite seu CPF no formulário de recuperação',
          'Você receberá instruções para redefinir sua senha',
          'Defina uma nova senha e faça login normalmente',
        ],
      },
      {
        title: 'Solicitar novo acesso',
        content: 'Novos colaboradores podem solicitar acesso ao sistema através do formulário de solicitação.',
        steps: [
          'Na tela de login, clique em "Solicitar novo acesso"',
          'Preencha seu nome, CPF, e-mail e filial desejada',
          'Informe o motivo da solicitação',
          'Aguarde a aprovação de um administrador',
        ],
        tip: 'A solicitação é enviada para os administradores da filial selecionada, que podem aprovar ou rejeitar o acesso.',
      },
    ],
  },
  {
    id: 'dashboard',
    group: 'Primeiros Passos',
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/3b63a93a7_generated_image.png',
    topics: [
      {
        title: 'Visão geral do Dashboard',
        content: 'O Dashboard é a página principal após o login. Ele apresenta métricas de segurança, gráficos analíticos e o feed de acessos recentes em tempo real.',
        steps: [
          'Após o login, você é redirecionado automaticamente para o Dashboard',
          'Visualize os cartões de métricas no topo: total de veículos, motoristas, acessos do dia e pendências',
          'Clique em qualquer cartão para navegar diretamente para a página correspondente',
          'Consulte os gráficos para análise de volume de acessos e status de veículos',
        ],
        tip: 'Os dados do Dashboard são atualizados em tempo real. Não é necessário recarregar a página para ver novos acessos.',
      },
      {
        title: 'Gráficos analíticos',
        content: 'O Dashboard inclui gráficos interativos que mostram o volume de acessos por período, distribuição de status de veículos e motoristas.',
        steps: [
          'Visualize o gráfico de barras com o volume de acessos ao longo do tempo',
          'Consulte o gráfico de pizza com a distribuição de status (validado, bloqueado, pendente)',
          'Use os filtros de período quando disponíveis para refinar a visualização',
        ],
      },
      {
        title: 'Feed de acessos recentes',
        content: 'Na parte inferior do Dashboard, o feed mostra os últimos acessos registrados na sua filial, com placa, motorista, status e horário.',
        steps: [
          'Role a página para baixo até a seção "Acessos Recentes"',
          'Cada item mostra a placa do veículo, nome do motorista, status e horário',
          'Clique em um item para ver mais detalhes do acesso',
        ],
      },
    ],
  },
  {
    id: 'acessos',
    group: 'Operação Diária',
    title: 'Acessos e Kanban',
    icon: 'ScanLine',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/e0f8a7c60_generated_image.png',
    topics: [
      {
        title: 'Registrar novo acesso',
        content: 'A página "Acessos" é o coração do sistema. Aqui você registra a entrada de veículos e motoristas, e gerencia o fluxo de liberação através do Kanban.',
        steps: [
          'Navegue até a página "Acessos" pelo menu',
          'No formulário de registro, digite a placa do veículo',
          'Digite o CPF do motorista (a formatação é aplicada automaticamente)',
          'O sistema cruza os dados na base centralizada em tempo real',
          'Se ambos estiverem validados, o acesso é registrado automaticamente no Kanban',
          'Se houver um acompanhante/ajudante, marque a opção e preencha os dados',
        ],
        tip: 'Veículos e motoristas não cadastrados aparecem como "Pendente de Revisão" no Kanban. Você pode solicitar o cadastro clicando no botão apropriado.',
      },
      {
        title: 'Fluxo do Kanban',
        content: 'O Kanban organiza os veículos em três colunas por status: Pendente de Revisão (laranja), Validado / Em Carga (verde) e Bloqueado (vermelho).',
        steps: [
          'Após registrar um acesso, o veículo aparece no Kanban na coluna correspondente ao seu status',
          'Veículos validados aparecem na coluna verde "Validado / Em Carga"',
          'Veículos pendentes aparecem na coluna laranja "Pendente de Revisão"',
          'Veículos bloqueados aparecem na coluna vermelha "Bloqueado"',
          'Administradores e encarregados podem mover cards entre as colunas',
        ],
        tip: 'O Kanban é atualizado em tempo real. Todos os operadores da filial veem as mudanças instantaneamente, sem necessidade de atualizar a página.',
      },
      {
        title: 'Aprovar acesso pendente',
        content: 'Quando um veículo ou motorista não está na base, o acesso fica como "Pendente de Revisão". Administradores e encarregados podem autorizá-lo.',
        steps: [
          'Localize o card na coluna "Pendente de Revisão" (laranja)',
          'Clique no botão "Autorizar" no card',
          'O sistema registra o nome e CPF de quem autorizou, com data e hora',
          'O operador que registrou o acesso é notificado em tempo real',
          'O card é movido para a coluna "Validado / Em Carga"',
        ],
      },
      {
        title: 'Bloquear acesso',
        content: 'Veículos ou motoristas com problemas podem ser bloqueados. O motivo do bloqueio é obrigatório.',
        steps: [
          'Localize o card do veículo no Kanban',
          'Clique no botão "Bloquear"',
          'Digite o motivo do bloqueio no campo obrigatório',
          'Confirme o bloqueio',
          'O operador que registrou o acesso será notificado com o motivo',
        ],
        tip: 'Veículos bloqueados não podem ser liberados até que um administrador altere o status de volta para "Validado" ou "Pendente de Revisão".',
      },
      {
        title: 'Liberar saída do veículo',
        content: 'Quando o veículo está pronto para sair, a saída pode ser liberada indicando se saiu vazio ou carregado.',
        steps: [
          'Localize o card na coluna "Validado / Em Carga" (verde)',
          'Clique no botão "Liberar Saída"',
          'Selecione se o veículo está saindo "Vazio" ou "Carregado"',
          'Adicione observações opcionais se necessário',
          'Confirme a liberação',
          'Todos os operadores da filial são notificados em tempo real',
        ],
      },
      {
        title: 'Solicitar cadastro de veículo/motorista',
        content: 'Se o veículo ou motorista não for encontrado na base, você pode solicitar o cadastro.',
        steps: [
          'Após tentar registrar um acesso com placa/CPF não encontrado, clique em "Solicitar Autorização de Cadastro"',
          'A solicitação é enviada para administradores e encarregados da mesma filial',
          'Aguarde a notificação de aprovação ou rejeição',
          'Após aprovação, o veículo/motorista fica disponível na base',
        ],
        tip: 'A solicitação inclui os dados informados e o motivo. O administrador pode aprovar, criar o registro na base e o sistema notifica o solicitante.',
      },
    ],
  },
  {
    id: 'verificacao-rapida',
    group: 'Operação Diária',
    title: 'Verificação Rápida',
    icon: 'Search',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/6051af465_generated_image.png',
    topics: [
      {
        title: 'Consultar veículo e motorista instantaneamente',
        content: 'A Verificação Rápida permite consultar o status de veículos e motoristas sem precisar registrar um acesso. Ideal para conferências rápidas na portaria.',
        steps: [
          'Acesse a página "Verificação Rápida" no menu Operação',
          'Digite a placa do veículo no campo "Placa do Veículo"',
          'Digite o CPF do motorista no campo "CPF do Motorista" (formatação automática)',
          'Clique em "Verificar" ou pressione Enter',
          'O sistema exibe os resultados em dois cartões: Veículo e Motorista',
          'Cada cartão mostra os dados cadastrais e o status atual (validado, bloqueado, pendente)',
        ],
        tip: 'Você pode pesquisar apenas por placa, apenas por CPF, ou por ambos simultaneamente. Os campos não preenchidos são ignorados na busca.',
      },
      {
        title: 'Interpretar os resultados',
        content: 'Após a busca, o sistema mostra o status de cada item encontrado com badges coloridos.',
        steps: [
          'Badge verde "Validado": o veículo/motorista está apto a acessar',
          'Badge vermelho "Bloqueado": o acesso está bloqueado, verifique o motivo',
          'Badge laranja "Pendente de Revisão": ainda não foi validado, aguarda aprovação',
          'Se o item não for encontrado, será exibida a mensagem "não encontrado"',
        ],
        tip: 'Dados como transportadora e observações também são exibidos para ajudar na decisão de liberar ou não o acesso.',
      },
    ],
  },
  {
    id: 'crdk',
    group: 'Operação Diária',
    title: 'Acesso CRDK — Transferências entre CDs',
    icon: 'Truck',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/4bba2397c_generated_image.png',
    topics: [
      {
        title: 'O que é o Acesso CRDK',
        content: 'Módulo dedicado ao registro de transferências de mercadorias entre centros de distribuição. As placas da carreta e do cavalo são registradas separadamente, e a saída exige verificação fotográfica da placa por inteligência artificial.',
        steps: [
          'Acesse a página "Acesso CRDK" no menu',
          'O módulo é independente do fluxo de Acessos comum',
          'Use este módulo especificamente para transferências entre CDs',
        ],
      },
      {
        title: 'Registrar entrada de transferência',
        content: 'O registro de entrada captura os dados do veículo, motorista e transferência.',
        steps: [
          'Preencha a "Placa da Carreta" (campo obrigatório)',
          'Preencha a "Placa do Cavalo" se houver',
          'Digite o "Nome" do motorista (campo obrigatório)',
          'Preencha "Empresa", "Destino" (padrão PR), "RG/CPF" e "Crachá"',
          'Preencha "Autorização/Contato" se aplicável',
          'Clique em "Registrar Entrada"',
          'O veículo entra com status "Validado em Descarregamento"',
        ],
        tip: 'O CPF é formatado automaticamente (000.000.000-00) no campo RG/CPF. A placa é convertida para maiúsculas automaticamente.',
      },
      {
        title: 'Liberar saída com verificação de placa por IA',
        content: 'Ao liberar a saída de uma transferência CRDK, o sistema exige uma foto do interior da carreta. A IA detecta e valida a placa automaticamente.',
        steps: [
          'Na lista de veículos em descarregamento, clique em "Liberar Saída"',
          'O sistema mostra qual placa é esperada para a verificação',
          'Tire uma foto do interior da carreta, com a placa visível',
          'O sistema usa IA para detectar o texto da placa na imagem',
          'Se a placa detectada coincidir com a registrada, a foto é aceita',
          'Se não coincidir, a foto é rejeitada e uma nova foto é solicitada',
          'Adicione observações sobre a saída se necessário',
          'Clique em "Confirmar Saída" para finalizar',
        ],
        tip: 'A placa deve estar visível, legível e bem iluminada na foto. Tire a foto de frente para a placa, sem obstruções, para garantir a leitura correta pela IA.',
      },
      {
        title: 'Exportar relatório CRDK',
        content: 'Você pode exportar um relatório PDF com todos os registros de transferência CRDK.',
        steps: [
          'Na página "Acesso CRDK", clique em "Exportar PDF"',
          'O sistema gera um relatório com todos os registros',
          'O PDF inclui placas, motorista, empresa, horários e fotos verificadas',
          'O arquivo é baixado automaticamente',
        ],
      },
    ],
  },
  {
    id: 'bloqueio',
    group: 'Gestão de Base',
    title: 'Painel de Bloqueio',
    icon: 'ShieldAlert',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/e0f8a7c60_generated_image.png',
    topics: [
      {
        title: 'Gestão de veículos e motoristas',
        content: 'O Painel de Bloqueio permite visualizar e gerenciar o status de todos os veículos e motoristas cadastrados no sistema.',
        steps: [
          'Acesse a página "Painel de Bloqueio" no menu',
          'Use as abas para alternar entre "Veículos" e "Motoristas"',
          'Cada item mostra o status atual com badge colorido',
          'Use os filtros para refinar a visualização por status e filial',
        ],
      },
      {
        title: 'Filtros e busca',
        content: 'Encontre rapidamente veículos ou motoristas específicos usando busca e filtros.',
        steps: [
          'Digite o termo de busca (placa, nome ou CPF) no campo de pesquisa',
          'Selecione um status no filtro (Todos, Validado, Bloqueado, Pendente)',
          'Selecione uma filial no filtro de filial',
          'Use a ordenação por data, nome ou status conforme necessário',
          'Navegue entre as páginas usando a paginação inferior',
        ],
      },
      {
        title: 'Atualizar status e adicionar comprovante',
        content: 'Administradores podem alterar o status de veículos e motoristas, e anexar comprovantes Opentech.',
        steps: [
          'Localize o veículo ou motorista desejado',
          'Clique no botão de editar (ícone de lápis)',
          'Altere o status (Validado, Bloqueado, Pendente de Revisão)',
          'Para anexar comprovante Opentech, faça upload da foto',
          'Salve as alterações — cada mudança é registrada no log de auditoria',
        ],
        tip: 'O upload do comprovante Opentech é importante para comprovar que a atualização foi realizada no sistema externo.',
      },
    ],
  },
  {
    id: 'editar-base',
    group: 'Gestão de Base',
    title: 'Editar Base de Dados',
    icon: 'Database',
    topics: [
      {
        title: 'Cadastrar e editar veículos e motoristas',
        content: 'A página "Editar Base de Dados" permite cadastrar novos veículos e motoristas, editar informações existentes e excluir registros.',
        steps: [
          'Acesse "Editar Base de Dados" no menu',
          'Use as abas para alternar entre Veículos e Motoristas',
          'Clique em "Novo" para cadastrar um novo registro',
          'Preencha os campos (placa para veículos; nome e CPF para motoristas)',
          'Para editar, clique no ícone de lápis ao lado do registro',
          'Para excluir, clique no ícone de lixeira e confirme',
        ],
        tip: 'O CPF é formatado automaticamente no formulário de motoristas. Todas as alterações são registradas no log de auditoria com o nome do operador.',
      },
      {
        title: 'Busca e filtros na base',
        content: 'Use a busca e os filtros para localizar registros específicos na base de dados.',
        steps: [
          'Digite o termo de busca no campo superior',
          'Filtre por status (Todos, Validado, Bloqueado, Pendente)',
          'Filtre por filial se aplicável',
          'Ordenne por data, nome ou status',
          'Use a paginação para navegar pelos resultados',
        ],
      },
    ],
  },
  {
    id: 'relatorios',
    group: 'Relatórios',
    title: 'Relatórios e Análises',
    icon: 'BarChart3',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/3b63a93a7_generated_image.png',
    topics: [
      {
        title: 'Relatórios de acessos',
        content: 'A página "Relatórios" apresenta gráficos analíticos do volume de acessos, status de veículos e motoristas, e tendências ao longo do tempo.',
        steps: [
          'Acesse a página "Relatórios" no menu',
          'Selecione o período desejado (7, 30 ou 90 dias)',
          'Visualize os gráficos de volume de acessos por período',
          'Consulte a distribuição de status de veículos e motoristas',
          'Use os filtros para refinar os dados exibidos',
        ],
      },
      {
        title: 'Relatório Personalizado',
        content: 'Crie relatórios personalizados escolhendo as colunas, status e período específicos.',
        steps: [
          'Acesse "Relatório Personalizado" no menu',
          'Selecione as colunas que deseja incluir no relatório',
          'Filtre por status de veículos/motoristas',
          'Defina o período (data inicial e data final)',
          'Clique em "Gerar Relatório"',
          'Exporte em PDF (com marca d\'água confidencial) ou Excel',
        ],
        tip: 'O PDF gerado inclui marca d\'água "Confidencial" para segurança da informação, em conformidade com a LGPD.',
      },
      {
        title: 'Resumo de Turnos',
        content: 'O Resumo de Turnos apresenta métricas de produtividade por operador, com filtros de data e status.',
        steps: [
          'Acesse "Resumo de Turnos" no menu',
          'Selecione o período (data inicial e data final)',
          'Visualize as métricas globais: total de acessos, validados, bloqueados',
          'Consulte a tabela de produtividade por operador',
          'Exporte o resumo em PDF ou CSV',
        ],
        tip: 'Os nomes dos operadores são exibidos de forma ofuscada na exportação para proteção de dados (LGPD).',
      },
    ],
  },
  {
    id: 'modelos',
    group: 'Relatórios',
    title: 'Modelos Corporativos',
    icon: 'LayoutGrid',
    topics: [
      {
        title: 'Controle de Veículos — Expedição',
        content: 'Relatório de veículos que saíram carregados da filial, com placa (carreta/cavalo), motorista, empresa, data e hora.',
        steps: [
          'Acesse "Modelos Corporativos" no menu',
          'Selecione o modelo "Controle de Veículos — Expedição"',
          'Defina o período (data inicial e data final)',
          'Clique em "Gerar"',
          'O relatório é exibido em formato de tabela pronta para impressão',
          'Use Ctrl+P ou o botão de impressão para imprimir',
        ],
      },
      {
        title: 'Controle de Veículos — Recebimento',
        content: 'Relatório de veículos que chegaram na filial, no mesmo formato do relatório de expedição.',
        steps: [
          'Acesse "Modelos Corporativos" no menu',
          'Selecione o modelo "Controle de Veículos — Recebimento"',
          'Defina o período desejado',
          'Clique em "Gerar" para visualizar o relatório',
          'Imprima ou exporte conforme necessário',
        ],
      },
      {
        title: 'Averbação Mensal e Semestral',
        content: 'Relatório de averbação com dados agrupados por prioridade e rota, exportável em PDF e Excel.',
        steps: [
          'Selecione o modelo "Averbação Mensal" ou "Averbação Semestral"',
          'Escolha o mês (para mensal) ou semestre (para semestral)',
          'Clique em "Gerar" para visualizar a tabela',
          'Exporte em PDF ou Excel usando os botões correspondentes',
        ],
        tip: 'O relatório de averbação inclui colunas padrão: Data de Embarque, Itinerário, UF Origem/Destino, Urbano (Sim para rotas 90/91) e Valor de Mercadoria.',
      },
    ],
  },
  {
    id: 'averbacao',
    group: 'Relatórios',
    title: 'Averbação',
    icon: 'FileSpreadsheet',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/96e7fdd15_generated_image.png',
    topics: [
      {
        title: 'Importar arquivo de averbação',
        content: 'A página "Averbação" permite importar arquivos .txt ou .csv com dados de averbação para processamento e armazenamento na base de dados.',
        steps: [
          'Acesse a página "Averbação" no menu',
          'Clique na área de upload ou arraste um arquivo .txt/.csv',
          'O sistema lê o arquivo e exibe os dados em formato de tabela',
          'Clique em "Visualizar" para ver todos os dados importados',
          'Selecione as colunas que deseja manter no processamento',
        ],
        tip: 'O sistema detecta automaticamente o delimitador do arquivo (tab, ponto e vírgula, vírgula, etc.) e separa as colunas corretamente.',
      },
      {
        title: 'Processar dados por prioridade',
        content: 'O processamento agrupa os dados por prioridade, somando colunas numéricas e consolidando valores.',
        steps: [
          'Após importar, clique em "Visualizar" para abrir o modal de processamento',
          'Selecione as colunas que deseja manter',
          'Clique em "Processar" para agrupar por prioridade',
          'O sistema soma as colunas numéricas (valores) e consolida as listas',
          'Para prioridades 90 e 91, os dados são agrupados por rota',
          'Clique em "Restaurar" para voltar aos dados originais sem processamento',
        ],
      },
      {
        title: 'Salvar na base de dados',
        content: 'Após processar, salve os dados na base de dados para consulta e relatórios futuros.',
        steps: [
          'Após processar, clique em "Salvar na Base de Dados"',
          'O sistema faz o desdobramento diário: um registro por data de embarque',
          'Cada registro contém o valor total da prioridade correspondente àquela data',
          'Registros existentes são atualizados (upsert), novos são criados',
          'A mensagem de confirmação mostra quantos foram atualizados e criados',
        ],
        tip: 'O salvamento usa lógica de upsert: se já existir um registro para o mesmo mês/dia/prioridade, ele é atualizado em vez de duplicado.',
      },
      {
        title: 'Consultar dados salvos e exportar',
        content: 'Os dados salvos ficam disponíveis para consulta com filtros de mês e dia, e podem ser exportados.',
        steps: [
          'Na seção "Dados Salvos", filtre por mês usando o seletor',
          'Use o filtro de dias (seleção múltipla por checkbox) para refinar',
          'Visualize os dados na tabela com agrupamento por prioridade',
          'Clique em "PDF" ou "Excel" para exportar os dados filtrados',
          'Clique em "Atualizar" para recarregar os dados',
        ],
        tip: 'O filtro de dias permite selecionar múltiplos dias simultaneamente. Use "Selecionar todos" para marcar todos os dias do mês.',
      },
    ],
  },
  {
    id: 'monitor',
    group: 'Monitoramento',
    title: 'Monitor de Filiais',
    icon: 'Activity',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/a2f485bee_generated_image.png',
    topics: [
      {
        title: 'Visão geral do Monitor',
        content: 'O Monitor de Filiais apresenta um dashboard com a saúde operacional de cada filial, incluindo métricas de veículos, motoristas e acessos.',
        steps: [
          'Acesse "Monitor de Filiais" no menu',
          'Visualize os cartões de saúde de cada filial',
          'Cada cartão mostra o score de saúde operacional (porcentagem)',
          'Consulte as métricas de veículos, motoristas e acessos por filial',
        ],
      },
      {
        title: 'Calendário operacional',
        content: 'Visualize as operações em formato de calendário mensal, com indicadores de volume por dia.',
        steps: [
          'Clique na aba "Calendário" no Monitor de Filiais',
          'Navegue entre meses usando as setas',
          'Cada dia mostra indicadores de operações (liberações, pendências)',
          'Clique em um dia para ver detalhes das operações daquele dia',
        ],
      },
      {
        title: 'Análise econômica',
        content: 'A aba de análise econômica apresenta dados financeiros segregados por filial.',
        steps: [
          'Clique na aba "Análise Econômica" no Monitor de Filiais',
          'Visualize gráficos de receita por filial',
          'Consulte o desempenho de rotas e prioridades',
          'Compare métricas entre filiais',
        ],
        tip: 'A análise econômica usa dados de averbação processados. Certifique-se de importar e salvar os dados de averbação para visualizar as métricas.',
      },
    ],
  },
  {
    id: 'supervisao',
    group: 'Monitoramento',
    title: 'Supervisão de Filiais',
    icon: 'DollarSign',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/a2f485bee_generated_image.png',
    topics: [
      {
        title: 'Dashboard consolidado de supervisão',
        content: 'A Supervisão de Filiais consolida dados de todas as filiais em um dashboard centralizado para supervisores e administradores.',
        steps: [
          'Acesse "Supervisão de Filiais" no menu (apenas supervisores e administradores)',
          'Visualize os cartões de KPIs consolidados (receita total, filiais ativas)',
          'Consulte os gráficos de tendências mensais',
          'Analise o desempenho por rota e categoria (urbano vs. não urbano)',
        ],
        tip: 'O acesso à Supervisão de Filiais é restrito a administradores e supervisores. Gestores e operadores não têm acesso a esta página.',
      },
      {
        title: 'Drill-down por filial',
        content: 'Clique em uma filial específica para ver a análise econômica detalhada.',
        steps: [
          'Na lista de filiais, clique em uma filial específica',
          'O sistema exibe a análise econômica detalhada da filial selecionada',
          'Visualize gráficos de receita, rotas e distribuição urbana',
          'Use os seletores de gráficos para personalizar a visualização',
        ],
      },
    ],
  },
  {
    id: 'notificacoes',
    group: 'Administração',
    title: 'Notificações',
    icon: 'Bell',
    topics: [
      {
        title: 'Central de notificações',
        content: 'A página "Notificações" centraliza todos os avisos do sistema, segmentados por filial e tipo.',
        steps: [
          'Acesse "Notificações" no menu',
          'Visualize as notificações não lidas (destacadas)',
          'Clique em uma notificação para marcar como lida',
          'Use o botão "Marcar todas como lidas" para limpar a lista',
        ],
        tip: 'As notificações push são auto-ocultáveis após 3 segundos. Acesse a página de Notificações para ver o histórico completo.',
      },
      {
        title: 'Tipos de notificação',
        content: 'O sistema possui quatro tipos de notificação, cada um com um ícone e cor distintos.',
        steps: [
          'Liberação de veículos: avisa quando um veículo foi liberado ou bloqueado',
          'Entrada/Saída: notifica sobre novos acessos e saídas registradas',
          'Documentação de motoristas: avisa sobre pendências de documentação',
          'Operações administrativas: notifica sobre ações administrativas do sistema',
        ],
      },
      {
        title: 'Enviar notificação',
        content: 'Envie notificações para usuários específicos ou para toda a filial.',
        steps: [
          'Na página de Notificações, clique em "Nova Notificação"',
          'Escolha o tipo de notificação',
          'Selecione o destinatário (usuário específico ou toda a filial)',
          'Digite o título e a mensagem',
          'Clique em "Enviar"',
        ],
        tip: 'Cada envio de notificação é registrado no log de auditoria com o nome do remetente.',
      },
    ],
  },
  {
    id: 'auditoria',
    group: 'Administração',
    title: 'Auditoria e Registros',
    icon: 'ScrollText',
    topics: [
      {
        title: 'Auditoria de Sistema',
        content: 'O log de auditoria registra todas as ações realizadas no sistema, com IP, domínio, dispositivo, categoria e data/hora.',
        steps: [
          'Acesse "Auditoria" no menu',
          'Visualize a aba "Logs de Sistema" com todas as ações registradas',
          'Filtre por categoria (login, veículo, motorista, busca, gestão de usuários, etc.)',
          'Use a busca por termo para encontrar ações específicas',
          'Filtre por intervalo de datas para análises temporais',
        ],
        tip: 'O log de auditoria é imutável e registra quem, quando e o que foi feito. É essencial para conformidade e segurança.',
      },
      {
        title: 'Registros de Acesso e Saída',
        content: 'A aba "Registros de Acesso" mostra todos os registros de entrada e saída, incluindo fotos anexadas.',
        steps: [
          'Na página de Auditoria, clique na aba "Registros de Acesso"',
          'Visualize os sub-tabs: "Logs de Acesso" e "Registros CRDK"',
          'Cada registro mostra placa, motorista, empresa, status, operador e horário',
          'Clique em um registro para ver detalhes e fotos anexadas',
        ],
      },
      {
        title: 'Exportar logs',
        content: 'Exporte os logs filtrados em PDF (com marca d\'água confidencial) ou Excel (CSV).',
        steps: [
          'Aplique os filtros desejados (categoria, data, termo de busca)',
          'Clique em "Exportar PDF" para um relatório formatado com marca d\'água',
          'Clique em "Exportar CSV" para uma planilha Excel',
          'O arquivo é baixado automaticamente',
        ],
        tip: 'A exportação de logs é restrita a administradores. Cada exportação é registrada no log de auditoria.',
      },
    ],
  },
  {
    id: 'gerenciamento-filiais',
    group: 'Administração',
    title: 'Gerenciamento de Filiais',
    icon: 'Building2',
    topics: [
      {
        title: 'Cadastrar e gerenciar filiais',
        content: 'A página "Gerenciamento de Filiais" permite cadastrar, editar e desativar filiais no sistema.',
        steps: [
          'Acesse "Gerenciamento de Filiais" no menu',
          'Clique em "Nova Filial" para cadastrar',
          'Preencha nome, código (ex: CD-PR), cidade e endereço',
          'Defina se a filial está ativa',
          'Para editar, clique no ícone de edição ao lado da filial',
          'Para desativar, alterne o status de ativo',
        ],
        tip: 'O código da filial é usado como identificador em todo o sistema. Escolha códigos descritivos (ex: CD-PR para Curitiba).',
      },
    ],
  },
  {
    id: 'config',
    group: 'Administração',
    title: 'Configurações do Sistema',
    icon: 'Settings',
    image: 'https://media.base44.com/images/public/6a52c95a887ed48b22b409b4/57d56652d_generated_image.png',
    topics: [
      {
        title: 'Gestão de usuários',
        content: 'Crie, edite ou remova colaboradores do sistema. Defina cargo, filiais permitidas e páginas com acesso.',
        steps: [
          'Acesse "Configurações" no menu',
          'Na aba "Usuários", clique em "Novo Usuário"',
          'Preencha nome, sobrenome, CPF, senha, matrícula e e-mail',
          'Defina o cargo (Administrador Master, Administrador, Encarregado, Operador, Visualizador)',
          'Selecione as filiais permitidas para o usuário',
          'Defina as páginas que o usuário pode acessar',
          'Salve as alterações',
        ],
        tip: 'O cargo determina o nível de acesso. Administrador Master tem acesso total; Visualizador apenas consulta. A matrícula é obrigatória.',
      },
      {
        title: 'Configurações de segurança',
        content: 'Defina políticas de segurança por cargo, incluindo tempo de sessão, tentativas de login e permissões.',
        steps: [
          'Acesse "Configurações de Segurança" no menu',
          'Selecione o cargo que deseja configurar',
          'Defina o tempo máximo de sessão em minutos',
          'Configure o máximo de tentativas de login antes do bloqueio',
          'Ative/desative permissões: exportar, importar, excluir registros',
          'Defina se o cargo exige autenticação de dois fatores (2FA)',
          'Configure restrição de IP se necessário',
          'Salve as configurações',
        ],
        tip: 'O sistema encerra sessões automaticamente nos horários de troca de turno (07:00 e 19:00) para segurança operacional.',
      },
      {
        title: 'Configurações de notificações',
        content: 'Personalize quais tipos de notificação cada usuário recebe.',
        steps: [
          'Acesse "Configurações de Notificações" no menu',
          'Para cada tipo, ative ou desative conforme a preferência do usuário:',
          '— Liberação de veículos',
          '— Entrada e saída',
          '— Documentação de motoristas',
          '— Operações administrativas',
          'Salve as alterações',
        ],
        tip: 'As configurações de notificação são individuais — cada usuário pode personalizar suas próprias preferências.',
      },
      {
        title: 'Backup e restauração',
        content: 'Realize backups manuais ou configure backups automáticos com criptografia.',
        steps: [
          'Acesse "Configurações" e navegue até a aba "Backup"',
          'Clique em "Backup Manual" para exportar todos os dados em JSON',
          'O backup inclui configurações, metadados e registros de todas as entidades',
          'Consulte o histórico de backups na mesma aba',
          'Para restaurar, use a função de importação na página "Exportar/Importar"',
        ],
        tip: 'Apenas administradores podem realizar backups. Cada operação de backup é registrada no log de auditoria.',
      },
    ],
  },
  {
    id: 'exportar',
    group: 'Administração',
    title: 'Exportar e Importar Dados',
    icon: 'Download',
    topics: [
      {
        title: 'Backup completo (JSON)',
        content: 'Exporte todos os dados do sistema em formato JSON para backup ou migração.',
        steps: [
          'Acesse "Exportar/Importar" no menu',
          'Na aba "Exportar", clique em "Backup Completo"',
          'O sistema coleta todas as entidades, configurações e metadados',
          'O arquivo JSON é baixado automaticamente',
        ],
        tip: 'Apenas administradores e administradores master podem exportar dados. A operação é registrada no log de auditoria.',
      },
      {
        title: 'Importação inteligente de Excel/CSV',
        content: 'Importe planilhas de veículos e motoristas. O sistema detecta automaticamente o tipo de dado e faz o mapeamento de colunas.',
        steps: [
          'Acesse "Exportar/Importar" e clique na aba "Importar"',
          'Selecione um arquivo Excel (.xlsx) ou CSV',
          'O sistema detecta automaticamente se são veículos ou motoristas',
          'O mapeamento de colunas é feito de forma inteligente',
          'Registros existentes são atualizados; novos são criados (upsert)',
          'O resultado mostra quantos registros foram criados e atualizados',
        ],
        tip: 'A importação usa lógica de upsert: se a placa ou CPF já existir na base, o registro é atualizado com os novos dados. Caso contrário, um novo registro é criado.',
      },
    ],
  },
  {
    id: 'perfil',
    group: 'Conta',
    title: 'Perfil e Termos de Uso',
    icon: 'User',
    topics: [
      {
        title: 'Visualizar e editar perfil',
        content: 'A página "Perfil" mostra seus dados cadastrais e permite atualizar informações pessoais.',
        steps: [
          'Acesse "Perfil" no menu',
          'Visualize seus dados: nome, CPF, cargo, filial, matrícula',
          'Atualize foto de perfil, telefone e e-mail se necessário',
          'Salve as alterações',
        ],
        tip: 'Dados como CPF e cargo são definidos pelo administrador e não podem ser alterados pelo próprio usuário.',
      },
      {
        title: 'Termos de Uso',
        content: 'Todo colaborador deve aceitar os Termos de Uso no primeiro acesso. O aceite é registrado com data e hora.',
        steps: [
          'No primeiro acesso, o sistema exibe o modal de Termos de Uso',
          'Leia atentamente todos os termos',
          'Clique em "Aceitar" para concordar com os termos',
          'O aceite é registrado no sistema com data e hora',
          'Você pode revisar os termos a qualquer momento na página "Termos de Uso"',
        ],
        tip: 'O aceite dos Termos de Uso é obrigatório. Sem o aceite, o acesso ao sistema é restrito.',
      },
      {
        title: 'Plano de Trabalho',
        content: 'A página "Plano de Trabalho" permite gerenciar tarefas e atribuir responsabilidades.',
        steps: [
          'Acesse "Plano de Trabalho" no menu',
          'Visualize suas tarefas pendentes e em andamento',
          'Crie novas tarefas com título, descrição, prioridade e data limite',
          'Atribua responsáveis quando aplicável',
          'Marque tarefas como concluídas conforme forem finalizadas',
        ],
      },
    ],
  },
];

export const FAQ = [
  { q: 'Como funciona o Kanban de veículos?', a: 'Na página "Acessos", após registrar um acesso, o veículo aparece no Kanban na coluna "Pendente de Revisão". Administradores e encarregados podem arrastar o card para "Validado" ou "Bloquear" com motivo. Na coluna "Validado", é possível liberar a saída informando se o veículo saiu vazio ou carregado.' },
  { q: 'Como liberar a saída de um veículo?', a: 'No Kanban, coluna "Validado", clique em "Liberar Saída". Selecione se o veículo está saindo "Vazio" ou "Carregado". Observações opcionais podem ser adicionadas. Todos os operadores da filial recebem notificação em tempo real.' },
  { q: 'O que é o Acesso CRDK?', a: 'É o módulo para registro de transferências de mercadorias entre centros de distribuição. As placas da carreta e do cavalo são registradas separadamente. Ao liberar a saída, o sistema tira uma foto do interior da carreta e verifica a placa automaticamente via IA.' },
  { q: 'Como funciona a verificação de placa na foto?', a: 'Ao liberar a saída de um CRDK, tire uma foto do interior da carreta. O sistema usa IA para detectar o texto da placa na imagem e compara com a placa registrada. Se coincidir, a foto é aceita. Se não, é rejeitada e você deve tirar uma nova foto. A placa deve estar visível, legível e bem iluminada.' },
  { q: 'Como solicitar cadastro de veículo/motorista não encontrado?', a: 'Na página "Acessos", se o veículo ou motorista não for encontrado na base, clique em "Solicitar Autorização de Cadastro". A solicitação vai para administradores e encarregados da sua filial, que podem aprovar ou negar. Você é notificado quando houver resposta.' },
  { q: 'Como usar a Verificação Rápida?', a: 'Acesse "Verificação Rápida" no menu. Digite a placa do veículo e/ou CPF do motorista nos campos. Clique em "Verificar". O sistema mostra os resultados com status (verde=validado, vermelho=bloqueado, laranja=pendente). Você pode pesquisar por placa, CPF ou ambos.' },
  { q: 'Como exportar relatórios?', a: 'Na página "Relatórios", selecione o período (7, 30 ou 90 dias) e visualize os gráficos. Em "Relatório Personalizado", escolha as colunas e status, e exporte em PDF (com marca d\'água) ou Excel. Em "Modelos Corporativos", gere relatórios prontos de Expedição e Recebimento.' },
  { q: 'Como importar dados via Excel?', a: 'Na página "Exportar/Importar", aba "Importar", selecione um arquivo Excel ou CSV. O sistema detecta automaticamente se são veículos ou motoristas e faz o mapeamento de colunas. Registros existentes são atualizados; novos são criados. Apenas administradores podem importar.' },
  { q: 'Como funciona a Averbação?', a: 'Importe um arquivo .txt/.csv na página "Averbação". O sistema exibe os dados em tabela. Clique em "Visualizar", selecione colunas e "Processar" para agrupar por prioridade. Clique em "Salvar na Base de Dados" para armazenar. Use os filtros de mês e dia para consultar e exportar em PDF/Excel.' },
  { q: 'Como funcionam as notificações por filial?', a: 'As notificações são segmentadas por filial — você só recebe avisos da sua unidade. Em "Configurações de Notificações", ajuste quais tipos deseja receber (liberação de veículos, entrada/saída, documentação, operações administrativas). Notificações push são auto-ocultáveis após 3 segundos.' },
  { q: 'Como fazer backup dos dados?', a: 'Em "Configurações", aba "Backup", clique em "Backup Manual" para exportar todos os dados em JSON. O histórico de backups é exibido na mesma aba. Apenas administradores podem realizar backups.' },
  { q: 'Por que os dados aparecem borrados?', a: 'Para proteção de dados (LGPD), dados sensíveis como CPF, CNH e placas são exibidos de forma ofuscada/borrada em listagens. Apenas o status é totalmente visível. Dados completos são acessíveis em operações específicas autorizadas.' },
  { q: 'Quem pode acessar a Supervisão de Filiais?', a: 'A Supervisão de Filiais é restrita a administradores e supervisores. Gestores e operadores não têm acesso a esta página. O menu aparece apenas para perfis autorizados.' },
  { q: 'O sistema funciona em celular e tablet?', a: 'Sim, o PROFARMA LIBERAAUTO PRO é responsivo e funciona em PC, tablet e celular. O design se adapta automaticamente ao tamanho da tela. A captura de fotos na saída CRDK usa a câmera do dispositivo.' },
];